name: Main

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #      - name: Build
      #        run: echo ${{ github.sha }} > Release.txt
      #      - name: Test
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: login
        run: echo //npm.pkg.github.com/:_authToken=${{secrets.GTH_TOKEN}} > ./.npmrc

      - name: out
        run: cat ./.npmrc

      - name: install
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GIT_TOKEN}}
      - name: build
        run: npm run build

      - name: build win
        run: npx pkg -t node18-win-x64 dist/src/app.js -o fufuu for windows.exe

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          if: startsWith(github.ref, 'publish~')
          tag_name: ${{ GITHUB_REF_NAME }}
          generated_release_notes: CHANGELOG.md
          files: |
            Release.txt
            app.exe
        env:
          GITHUB_TOKEN: ${{secrets.GIT_TOKEN}}